/**
 * KTX2TextureLoader — KTX2 texture compression pipeline with fallback.
 *
 * Attempts to load KTX2 compressed textures for maximum GPU efficiency.
 * Falls back to CanvasTexture (procedurally generated by PBRTextures) if:
 *   - KTX2 file doesn't exist on disk
 *   - KTX2Loader is unavailable
 *   - Browser doesn't support Basis Universal
 *
 * KTX2 benefits (Phase D4 of the masterplan):
 *   - 70% smaller GPU memory than uncompressed (block-compressed on GPU)
 *   - Hardware-decoded on most GPUs (no per-pixel decode in shader)
 *   - Supports ETC1S (small file) and UASTC (high quality) modes
 *   - Disproportionately important for mobile/Android targets — uncompressed
 *     PNG/JPG textures are decompressed to full RGBA8 in GPU memory regardless
 *     of file size, and mid-range Android devices have far less VRAM headroom
 *     than a gaming PC.
 *
 * Usage (async):
 *   const loader = await getKTX2Loader();
 *   const tex = await loader.load('/textures/asphalt.ktx2', canvasFallbackTexture);
 *
 * Design notes:
 *   - Loader init is async (must call detectSupport on the renderer), so we
 *     expose a getKTX2Loader() singleton getter rather than constructing
 *     synchronously.
 *   - The async constructor pattern used previously was broken (constructors
 *     cannot be async). Fixed to a static async init() method.
 *   - PBRTextures.js uses this loader opportunistically: it always returns a
 *     usable texture synchronously (the canvas fallback) and then SWAPS to
 *     the KTX2 version async if one becomes available.
 */
import * as THREE from 'three';

let _ktx2Loader = null;
let _initPromise = null;

/**
 * Initialize the KTX2Loader singleton. Idempotent — multiple callers share
 * the same init promise. Must run after at least one WebGLRenderer exists
 * so detectSupport() can probe capabilities.
 */
async function _initKTX2Loader() {
  if (_ktx2Loader) return _ktx2Loader;
  try {
    const { KTX2Loader } = await import('three/examples/jsm/loaders/KTX2Loader.js');
    _ktx2Loader = new KTX2Loader();
    _ktx2Loader.setTranscoderPath('https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/libs/basis/');
    // Try to detect support from the active game renderer if available.
    // The game exposes itself as window.__game and the Renderer wrapper
    // exposes the underlying THREE.WebGLRenderer as .renderer.
    const webglRenderer = window.__game?.renderer?.renderer || null;
    if (webglRenderer) {
      _ktx2Loader.detectSupport(webglRenderer);
    } else {
      // No renderer yet — defer detectSupport to first .load() call,
      // which will retry finding the renderer.
      console.warn('[KTX2] No renderer available at init; detectSupport deferred');
    }
    console.log('[KTX2] Loader initialized, compressed textures supported');
    return _ktx2Loader;
  } catch (e) {
    console.warn('[KTX2] Loader unavailable, using canvas texture fallback:', e.message);
    _ktx2Loader = null;
    return null;
  }
}

/**
 * Get the KTX2Loader singleton, initializing if needed. Multiple callers
 * share the same init promise — safe to call from anywhere.
 * Returns null if KTX2 is unavailable (loader threw or module missing).
 */
export async function getKTX2Loader() {
  if (!_initPromise) _initPromise = _initKTX2Loader();
  const loader = await _initPromise;
  return loader;
}

/**
 * Probe whether KTX2 init succeeded. Non-async — just checks the cached
 * singleton. Use this for "should we even try?" decisions in sync code.
 * Note that a true return means the loader is initialized; it does NOT
 * mean a specific .ktx2 file exists — file existence is only known after
 * an actual load attempt.
 */
export function isKTX2Supported() {
  return _ktx2Loader !== null;
}

/**
 * Load a texture — tries KTX2 first, falls back to the provided canvas/procedural
 * texture if KTX2 is unavailable or the file doesn't exist.
 *
 * @param {string} ktx2Path - path to .ktx2 file (e.g., '/textures/asphalt.ktx2')
 * @param {THREE.Texture} fallback - texture to return if KTX2 unavailable or fails.
 *                                    Caller is responsible for generating the fallback.
 * @returns {Promise<THREE.Texture>} resolves to the KTX2 texture if loaded, else fallback.
 */
export async function loadKTX2(ktx2Path, fallback) {
  const loader = await getKTX2Loader();
  if (!loader) return fallback;
  try {
    // If renderer wasn't ready at init time, try again now — game might be ready.
    const webglRenderer = window.__game?.renderer?.renderer || null;
    if (webglRenderer) loader.detectSupport(webglRenderer);

    const texture = await new Promise((resolve, reject) => {
      loader.load(ktx2Path, resolve, undefined, reject);
    });
    texture.colorSpace = THREE.SRGBColorSpace;
    texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
    texture.anisotropy = 8;
    console.log(`[KTX2] Loaded compressed texture: ${ktx2Path}`);
    return texture;
  } catch (e) {
    // KTX2 load failed (file missing, network error, format unsupported, etc.)
    // — fall back silently to the procedural texture.
    console.warn(`[KTX2] Failed to load ${ktx2Path}, using fallback:`, (e?.message || e).substring?.(0, 80) || e);
    return fallback;
  }
}
